FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build

ENV PORT 4004
ENV SERVICE_NAME "Hotel service"
ENV DATABASE_URL "postgresql://user:password@localhost:5432/hotel_db?schema=public"

EXPOSE 4004

CMD ["npm", "run", "build"]