FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build

ENV PORT 4007
ENV SERVICE_NAME "User service"
ENV DATABASE_URL "postgresql://user:password@localhost:5432/payment_db?schema=public"

EXPOSE 4007

CMD ["npm", "run", "build"]