FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build

ENV PORT 4005
ENV SERVICE_NAME "Booking service"
ENV DATABASE_URL "postgresql://user:password@localhost:5432/booking_db?schema=public"

EXPOSE 4005

CMD ["npm", "run", "build"]