FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install --frozen-lockfile

COPY . .

RUN npm run build

ENV PORT 4006
ENV SERVICE_NAME "Hotel service"
ENV DATABASE_URL "postgresql://user:password@localhost:5432/review_db?schema=public"

EXPOSE 4006

CMD ["npm", "run", "build"]